FROM ubuntu:latest

RUN apt update && apt install -y \
	snort \
	iproute2 \
	iptables \
	tcpdump && \
	rm -rf /var/lib/apt/lists/*

COPY config/snort.conf /etc/snort/snort.conf
COPY config/rules/local.rules /etc/snort/rules/local.rules

CMD ["snort", "-A", "fast", "-q", "-c", "/etc/snort/snort.conf", "-i", "eth0"] 
