FROM ubuntu:20.04

# Installer Snort et dépendances nécessaires
RUN apt-get update && apt-get install -y \
  snort \
  iproute2 \
  iputils-ping \
  net-tools \
  curl \
  && rm -rf /var/lib/apt/lists/*

# Ajouter les fichiers de configuration de Snort
COPY ./config/rules /etc/snort/rules/
COPY ./config/snort.conf /etc/snort/snort.conf

# Définir la commande par défaut
CMD ["snort", "-A", "console", "-c", "/etc/snort/snort.conf", "-i", "eth0", "-Q", "--daq", "afpacket"]

